---
- name: Check if Helm is installed
  ansible.builtin.command: "helm version --short"
  register: helm_version
  ignore_errors: true

- name: Install Helm on the target machine
  ansible.builtin.shell:
    cmd: |
      curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  when: helm_version.rc != 0
  args:
    warn: false
  when: ansible_distribution != "CoreOS"

- name: Extract the first IP from MetalLB IP range
  ansible.builtin.set_fact:
    metal_lb_first_ip: "{{ metal_lb_ip_range.split('-')[0] }}"

- name: Install NGINX Ingress controller using Helm with dynamic IP
  community.kubernetes.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    release_name: ingress-nginx
    namespace: ingress-nginx
    state: present
    values:
      controller:
        service:
          loadBalancerIP: "{{ metal_lb_first_ip }}"  # Dynamically extracted IP from MetalLB range
    update_repo_cache: true

- name: Verify Ingress controller service with dynamic IP
  ansible.builtin.command:
    cmd: "kubectl get svc -n ingress-nginx ingress-nginx-controller -o yaml"
  register: ingress_controller_svc_output

- name: Output Ingress controller service details
  ansible.builtin.debug:
    var: ingress_controller_svc_output.stdout
